language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="passcore:latest"

script:
  - |
    (
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
      docker push "$image"
    )
after_script:
  - docker images
