language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

#before_script:
#  - image="passcore:latest"

script:
  - |
    (
      docker build -t "ytianxia6/passcore:latest" .
      ~/official-images/test/run.sh "ytianxia6/passcore:latest"
      docker push "ytianxia6/passcore:latest"
    )
after_script:
  - docker images
